### ISSUE TITLE
Utilize .NET SDK referenced assemblies for better .NET support

### ISSUE THREAD

**Issue by lextm** [obfuscar/obfuscar#553]
### Is your feature request related to a problem? Please describe.

Currently to obfuscate a .NET assembly, end users might need to add custom search paths so that Obfuscar can locate the dependent assemblies.

### Describe the solution you'd like

Microsoft put referenced assemblies for `Microsoft.NETCore.App.Ref`, `Microsoft.AspNetCore.App.Ref`, and `NETStandard.Library.Ref`. If Obfuscar can automatically detect their presence and add them to the search paths, then end user configuration might be simplified.

**Comment by lextudio-support** [comment]
New issues are marked as low priority by default. [Becoming our commercial customers](https://docs.lextudio.com/services/consulting), and then your reports are handled with higher priority after triage.

**Comment by lextm** [comment]
Some basic code has been added in 637e331260053e60037d881a6c21e73f9ffa25e6 and will be shipped in vNext.

**Comment by lextm** [comment]
Shipped in release 2.2.42.

**Comment by Shazwazza** [comment]
As a workaround for anyone using ADO pipelines, i've done this

```yml
    - task: UseDotNet@2
      displayName: 'Install .NET 10'
      name: install_dotnet_10
      inputs:
        version: 10.0.x
    
    # Capture the exact .NET installation path for use in obfuscar
    - pwsh: |
        # The UseDotNet task sets DOTNET_ROOT as an environment variable
        $dotnetPath = $env:DOTNET_ROOT
        Write-Host "DOTNET_ROOT is: $dotnetPath"
        
        # Find the exact ASP.NET Core shared framework path
        $aspNetCorePath = Get-ChildItem -Path "$dotnetPath\shared\Microsoft.AspNetCore.App" -Directory | Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty FullName
        Write-Host "ASP.NET Core path: $aspNetCorePath"
        
        # Set as environment variable for use in obfuscar
        Write-Host "##vso[task.setvariable variable=DOTNET_ASPNETCORE_PATH]$aspNetCorePath"
        Write-Host "##vso[task.setvariable variable=DOTNET_INSTALL_PATH]$dotnetPath"
      displayName: 'Capture .NET installation paths'
```

Then in the obfuscar file:

```xml
<AssemblySearchPath path="%DOTNET_ASPNETCORE_PATH%" />
```
